### PR TITLE
Prefer alpine instead of debian

### PR DESCRIPTION
**Pull request by juandebravo**
Debian: 1.05 GB
Alpine:  231 MB

### CODE REVIEW

**Comment by fippo** [comment]
I blame @ggarber for this ;-)

**Comment by juandebravo** [comment]
it's a good choice to start, but at some point you realize having slim images have some benefits :)

**Comment by ggarber** [comment]
@fippo You ok with the `REGISTRY:=juandebravo` change in this PR? :)

**Comment by fippo** [comment]
yes, @juandebravo is cool :-)

**Pull request merged**
